server:
  port: 8081
  servlet:
    session:
      timeout: 21600

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: 56520
      url: jdbc:mysql://192.168.221.1:3307/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true